apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ynck
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ynck
    app.kubernetes.io/part-of: byoc-app-jqwh
  name: ynck
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: ynck
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: ynck
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-iwwr-tenant/byoc-app-jqwh/ynck@sha256:123e11737e259cf2d0303e6dd3fd8af29f53b11379acb8a7e2398dd229bdfaa5
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
