apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ynck
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ynck
    app.kubernetes.io/part-of: byoc-app-jqwh
  name: ynck
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: ynck
status:
  loadBalancer: {}
